services:
  - type: web
    name: resort-booking-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
